import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomAppBar from "@/components/BottomAppBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="bg-gray-300">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full max-w-[500px] m-auto bg-white`}
      >
        {children}
        <BottomAppBar />
      </body>
    </html>
  );
}
